                            List of relations
 Schema |                    Name                    |   Type   |  Owner  
--------+--------------------------------------------+----------+---------
 public | attachments                                | table    | redmine
 public | attachments_id_seq                         | sequence | redmine
 public | auth_sources                               | table    | redmine
 public | auth_sources_id_seq                        | sequence | redmine
 public | boards                                     | table    | redmine
 public | boards_id_seq                              | sequence | redmine
 public | changes                                    | table    | redmine
 public | changes_id_seq                             | sequence | redmine
 public | changeset_parents                          | table    | redmine
 public | changesets                                 | table    | redmine
 public | changesets_id_seq                          | sequence | redmine
 public | changesets_issues                          | table    | redmine
 public | comments                                   | table    | redmine
 public | comments_id_seq                            | sequence | redmine
 public | custom_field_enumerations                  | table    | redmine
 public | custom_field_enumerations_id_seq           | sequence | redmine
 public | custom_fields                              | table    | redmine
 public | custom_fields_id_seq                       | sequence | redmine
 public | custom_fields_projects                     | table    | redmine
 public | custom_fields_roles                        | table    | redmine
 public | custom_fields_trackers                     | table    | redmine
 public | custom_values                              | table    | redmine
 public | custom_values_id_seq                       | sequence | redmine
 public | documents                                  | table    | redmine
 public | documents_id_seq                           | sequence | redmine
 public | email_addresses                            | table    | redmine
 public | email_addresses_id_seq                     | sequence | redmine
 public | enabled_modules                            | table    | redmine
 public | enabled_modules_id_seq                     | sequence | redmine
 public | enumerations                               | table    | redmine
 public | enumerations_id_seq                        | sequence | redmine
 public | groups_users                               | table    | redmine
 public | import_items                               | table    | redmine
 public | import_items_id_seq                        | sequence | redmine
 public | imports                                    | table    | redmine
 public | imports_id_seq                             | sequence | redmine
 public | issue_categories                           | table    | redmine
 public | issue_categories_id_seq                    | sequence | redmine
 public | issue_relations                            | table    | redmine
 public | issue_relations_id_seq                     | sequence | redmine
 public | issue_statuses                             | table    | redmine
 public | issue_statuses_id_seq                      | sequence | redmine
 public | issues                                     | table    | redmine
 public | issues_id_seq                              | sequence | redmine
 public | journal_details                            | table    | redmine
 public | journal_details_id_seq                     | sequence | redmine
 public | journals                                   | table    | redmine
 public | journals_id_seq                            | sequence | redmine
 public | member_roles                               | table    | redmine
 public | member_roles_id_seq                        | sequence | redmine
 public | members                                    | table    | redmine
 public | members_id_seq                             | sequence | redmine
 public | messages                                   | table    | redmine
 public | messages_id_seq                            | sequence | redmine
 public | news                                       | table    | redmine
 public | news_id_seq                                | sequence | redmine
 public | open_id_authentication_associations        | table    | redmine
 public | open_id_authentication_associations_id_seq | sequence | redmine
 public | open_id_authentication_nonces              | table    | redmine
 public | open_id_authentication_nonces_id_seq       | sequence | redmine
 public | projects                                   | table    | redmine
 public | projects_id_seq                            | sequence | redmine
 public | projects_trackers                          | table    | redmine
 public | queries                                    | table    | redmine
 public | queries_id_seq                             | sequence | redmine
 public | queries_roles                              | table    | redmine
 public | repositories                               | table    | redmine
 public | repositories_id_seq                        | sequence | redmine
 public | roles                                      | table    | redmine
 public | roles_id_seq                               | sequence | redmine
 public | roles_managed_roles                        | table    | redmine
 public | schema_migrations                          | table    | redmine
 public | settings                                   | table    | redmine
 public | settings_id_seq                            | sequence | redmine
 public | time_entries                               | table    | redmine
 public | time_entries_id_seq                        | sequence | redmine
 public | tokens                                     | table    | redmine
 public | tokens_id_seq                              | sequence | redmine
 public | trackers                                   | table    | redmine
 public | trackers_id_seq                            | sequence | redmine
 public | user_preferences                           | table    | redmine
 public | user_preferences_id_seq                    | sequence | redmine
 public | users                                      | table    | redmine
 public | users_id_seq                               | sequence | redmine
 public | versions                                   | table    | redmine
 public | versions_id_seq                            | sequence | redmine
 public | watchers                                   | table    | redmine
 public | watchers_id_seq                            | sequence | redmine
 public | wiki_content_versions                      | table    | redmine
 public | wiki_content_versions_id_seq               | sequence | redmine
 public | wiki_contents                              | table    | redmine
 public | wiki_contents_id_seq                       | sequence | redmine
 public | wiki_pages                                 | table    | redmine
 public | wiki_pages_id_seq                          | sequence | redmine
 public | wiki_redirects                             | table    | redmine
 public | wiki_redirects_id_seq                      | sequence | redmine
 public | wikis                                      | table    | redmine
 public | wikis_id_seq                               | sequence | redmine
 public | workflows                                  | table    | redmine
 public | workflows_id_seq                           | sequence | redmine
(100 rows)

